### ISSUE TITLE
Got an issue with node. See comment for error

### ISSUE THREAD

**Issue by hkgrov** [cammiida/ProgramvareUtviklingGroup50#23]
Student has logged on to lecture 1
/Users/hakongrov/Documents/INDØK/2.År/2.Semester/Programvareutvikling/GIT/ProgramvareUtviklingGroup50/thoth/node/server.js:43
      lectures[lectureid]['students'].push(socket);
                         ^

TypeError: Cannot read property 'students' of undefined
    at Socket.<anonymous> (/Users/hakongrov/Documents/INDØK/2.År/2.Semester/Programvareutvikling/GIT/ProgramvareUtviklingGroup50/thoth/node/**server.js:43:26)**
    at emitTwo (events.js:106:13)
    at Socket.emit (events.js:191:7)
    at /Users/hakongrov/Documents/INDØK/2.År/2.Semester/Programvareutvikling/GIT/ProgramvareUtviklingGroup50/thoth/node/node_modules/socket.io/lib/socket.js:503:12
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
dhcp-10-22-14-137:node hakongrov$

**Comment by hkgrov** [comment]
I got this error when logging on to a lecture that should not be active with a student user. The feedback tab were visible, but I had not yet logged in with a teacher user and started this lecture.
